version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_movies
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env

  cache:
    container_name: redis
    image: redis
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server